// Generated by `{{MODULE_NAME}}`

import { useBemFactory } from '{{MODULE_NAME}}/use-bem-factory';

/**
 * Function to create classes according to the BEM methodology for a BEM block with the specified `name`.
 * If `name` is not specified or `null`, the name of the component where the composable is called will be used (if possible to define).
 *
 * @example
 *   const b = useBem('block');
 *   b(null); // block
 *   b('element', { modifier: true }); // block__element block__element--modifier
 * @example
 *   <script setup>
 *     defineOptions({ name: 'the-block' });
 *
 *     const b = useBem();
 *     b('element'); // the-block__element
 *   </script>
 *
 * @param   name   BEM block name.
 *
 * @returns        Function to create classes according to the BEM methodology.
 */
export const useBem = useBemFactory({{OPTIONS}});